---
- name: Install Docker
  hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: Remove docker packages installed from Debian repositories
      ansible.builtin.apt:
        name: "{{ item }}"
        state: absent
        purge: true
      with_items:
        - containerd
        - docker
        - docker-engine
        - docker.io
        - runc

    - name: Install GPG key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/debian/gpg
        keyring: /etc/apt/trusted.gpg.d/docker.gpg
        state: present

    - name: Register Docker APT repository
      ansible.builtin.apt_repository:
        repo: deb https://download.docker.com/linux/debian bookworm stable
        state: present
        filename: docker # /etc/apt/sources.list.d/docker.list
        update_cache: true

    - name: Install Docker packages
      ansible.builtin.apt:
        pkg:
          - containerd.io
          - docker-buildx-plugin
          - docker-ce
          - docker-ce-cli
          - docker-compose-plugin
