---
- name: Install Iosevka font 
  hosts: all
  become: true

  tasks:
    - name: Install font
      ansible.builtin.apt:
        update_cache: true
        deb: http://sid.ethz.ch/debian/fonts-iosevka/fonts-iosevka_22.0.0%2Bds-1_all.deb 
